HSEARCH-2632 Improve deserialization of batch parameters/properties
yrodiere/hibernate-search pull request #14
Opened 2017-05-07 16:47 UTC by mincong-h

Hi @yrodiere , here's the PR for <https://hibernate.atlassian.net/browse/HSEARCH-2632>.

2017-05-08 21:06 UTC, mincong-h commented
**Validation: as a listener or as a step?** Currently, the validation is handled as a listener, which means that its execution happens `#beforeJob()`. This is good enough is it were the only job-level listener. However, it's not the case because we also have another listener, `JobContextSetupListener`, and I think the validation should happen before job context setup. In the spec, I didn't see detail about the execution order among different listeners. To ensure the correct order, should we move the validation listener to an additional step—the first step before all the other ones? (And we need to change `JobContextSetupListener` accordingly) What do you think?

2017-05-10 13:20 UTC, yrodiere requested changes
Here are my comments, and below a few more general ones. This is a great start, but I think it needs a bit more polishing :)

First, as you mentioned, there is the problem of when validation occurs. Adding a step won't cut it, because we want to re-execute the validation on restart (the parameters may be different on restart), and already executed steps will not be re-executed on restart. I think your easiest way out is to simply move the validation code to JobContextSetupListener, for example in a `validateParameters` method called at the very top of `beforeJob`.

Then, I think a bit more work is needed to make all deserializations consistent; for instance, `PartitionMapper#buildPartitionUnitsFrom` still uses Integer.parse. Shouldn't it use our own deserialization util? Of course that's just one example, I expect other classes to have the same kind of problem (`EntityReader` in particular). But before addressing that, please consider turning the `DeserializationBuilder` into simple static methods, as explained in my comments below.

2017-05-10 13:20 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/impl/util/SerializationUtil.java
> +	public static DeserializationBuilder forParameter(String parameterName) {
I think a builder isn't necessary in this case... You could just have added three methods: `parseBooleanParameter` `parseIntegerParameter` and `parseParameter`. Especially because the three methods have no common code.

2017-05-10 13:20 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/massindexing/impl/steps/lucene/CheckpointAlgorithm.java
> -public class CheckpointAlgorithm extends AbstractCheckpointAlgorithm {
This has nothing to do with HSEARCH-2632. Please remove this commit, create a dedicated JIRA ticket, and submit another PR with only this commit.

2017-05-10 13:45 UTC, mincong-h commented
I always learnt new things from your review feedback, which is really great :+1: I'll rework it this week. Thanks!

2017-05-11 21:27 UTC, mincong-h commented
Yoann, I didn't finished the modification yet. I'll let you know when this PR is ready to be reviewed again.

2017-05-13 08:29 UTC, mincong-h commented
Please review again.

2017-05-15 07:26 UTC, merged

2017-05-15 07:27 UTC, yrodiere commented
Thanks! Merged. I just split the first commit in two and simplified the test about criteria serialization.

2017-05-15 07:44 UTC, mincong-h commented
Thx. Elegant code about the simplification @yrodiere :+1: