HSEARCH-2627 Use a proper JBoss Logger to log and to throw exceptions
yrodiere/hibernate-search pull request #8
Opened 2017-04-03 20:14 UTC by mincong-h

Hi Yoann, here's the PR for https://hibernate.atlassian.net/browse/HSEARCH-2627

2017-04-04 08:27 UTC, yrodiere requested changes
Thanks! Here are my two cents. Just a few changes and we'll be good to go. I added one commit to fix a problem that I should have addressed sooner.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +				throw log.cannotRetrieveEntityManagerFactoryInJsr352();
Just noticed I forgot to propagate the cause; I'll add a commit for that.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +			throw log.ambiguousEntityManagerFactoryInJsr352();
Same as above, I'll add a commit.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +					throw log.noAvailableEntityManagerFactoryInCDI(reference);
Funny that checkstyle let this through; there should be spaces before and after "reference".

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +				throw log.unknownEntityManagerFactoryScope(scopeName);
Same as above, there should be spaces before and after "scopeName".

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/context/jpa/impl/ActiveSessionFactoryRegistry.java
> +							org.hibernate.cfg.AvailableSettings.SESSION_FACTORY_NAME
No need to make this a parameter, you can embed it in the message annotation on the logger.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void analyzeIndexProgress(StringBuilder stringBuilder);
Maybe we should rather pass a string here? A bit strange to require a StringBuilder.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	@LogMessage(level = DEBUG)
This should definitely be `level = TRACE`. It is going to be very verbose.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void jobExecutionInfo(long executionId, BatchStatus batchStatus, int sleepInMillis);
This is never used and should be removed.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void readingEntities();
This should definitely be `level = TRACE`. It is going to be very verbose.
By the way, the method using this log only reads *one* entity, so maybe the message should change.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void isClosed(String simpleClassName);
If I understand correctly, the purpose of this message is to trace the opening/closing of the docwriter. So, why not call this "closingDocWriter" and make the message "Closing DocWriter for entity %1$s"?

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void isOpened(String simpleClassName);
Same as above, I think this should be renamed "openingDocWriter" and the message should be "Opening DocWriter for entity %1$s"?

2017-04-04 08:27 UTC, yrodiere commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void sessionClosed();
I don't see the point of those "xxxClosed" methods. We expect the job to close resources correctly, so we should only log stuff when the job *cannot* close it. I think we should those "xxxClosed" methods; same for `closingEverything`.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +				throw log.cannotRetrieveEntityManagerFactoryInJsr352();
Commit added.

2017-04-04 08:27 UTC, yrodiere commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +			throw log.ambiguousEntityManagerFactoryInJsr352();
Commit added.

2017-04-04 20:34 UTC, mincong-h commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void isClosed(String simpleClassName);
Actually, I was planned to use this method for logging the method `close()` in both `EntityReader` and `LuceneDocWriter`, but I only added it to the writer... That's why the method looks so weird. The `simpleClassName` should be either `EntityReader` or `LuceneDocWriter`.

I'll rework it.

2017-04-04 21:05 UTC, mincong-h commented on jsr352/cdi/src/main/java/org/hibernate/search/jsr352/cdi/context/jpa/impl/CDIEntityManagerFactoryRegistry.java
> +					throw log.noAvailableEntityManagerFactoryInCDI(reference);
My bad, I didn't format the code after the modification!

2017-04-04 21:06 UTC, mincong-h commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/context/jpa/impl/ActiveSessionFactoryRegistry.java
> +							org.hibernate.cfg.AvailableSettings.SESSION_FACTORY_NAME
Nice point!

2017-04-04 21:06 UTC, mincong-h commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void analyzeIndexProgress(StringBuilder stringBuilder);
+1

2017-04-04 21:08 UTC, mincong-h commented on jsr352/core/src/main/java/org/hibernate/search/jsr352/logging/impl/Log.java
> +	void sessionClosed();
You're right. Previously, I didn't know how to debug in my IDE, so I print log to debug—that's why there're a lot of no-sense log here.

2017-04-06 15:57 UTC, yrodiere approved these changes

2017-04-06 15:59 UTC, merged

2017-04-06 15:59 UTC, yrodiere commented
Nice! Shashed and merged, thanks!